# Generated by Django 3.2 on 2023-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'User'),
                    ('admin', 'Admin'),
                    ('moderator', 'Moderator'),
                ],
                default='user',
                max_length=30,
            ),
        ),
    ]
